[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "apprepocl"
version = "0.1.0"
description = "Application repository management module"
# authors = [
#     { name = "Nathan Loewenthal", email = "you@example.com" }
# ]
readme = "README.md"
license = { text = "MIT" }
dependencies = ["requests>=2.28"]

[tool.setuptools.packages.find]
where = ["src"]
